import importlib
import inspect
import fnmatch
from io import TextIOWrapper
import os


def write_classes(f: TextIOWrapper, patterns: list[str], module_name: str, title: str, description: str = '', exclude: list[str] = []) -> None:
    """Write the classes to the file."""
    module = importlib.import_module(module_name)

    classes = [
        name for name, obj in inspect.getmembers(module, inspect.isclass)
        if (obj.__module__ == module_name and
            any(fnmatch.fnmatch(name, pat) for pat in patterns if pat not in exclude) and
            obj.__doc__ and '(Automatic generated stub)' not in obj.__doc__)
    ]

    if description:
        f.write(f'{description}\n\n')

    write_dochtree(f, title, classes)

    for cls in classes:
        with open(f'docs/source/_autogenerated/{cls}.md', 'w') as f2:
            f2.write(f'# {module_name}.{cls}\n')
            f2.write('```{eval-rst}\n')
            f2.write(f'.. autoclass:: {module_name}.{cls}\n')
            f2.write('   :members:\n')
            f2.write('   :undoc-members:\n')
            f2.write('   :show-inheritance:\n')
            f2.write('   :inherited-members:\n')
            f2.write('```\n\n')


def write_functions(f: TextIOWrapper, patterns: list[str], module_name: str, title: str, description: str = '', exclude: list[str] = []) -> None:
    """Write the classes to the file."""
    module = importlib.import_module(module_name)

    functions = [
        name for name, obj in inspect.getmembers(module, inspect.isfunction)
        if (obj.__module__ == module_name and
            any(fnmatch.fnmatch(name, pat) for pat in patterns if pat not in exclude))
    ]

    if description:
        f.write(f'{description}\n\n')

    write_dochtree(f, title, functions)

    for func in functions:
        if not func.startswith('_'):
            with open(f'docs/source/_autogenerated/{func}.md', 'w') as f2:
                f2.write(f'# {module_name}.{func}\n')
                f2.write('```{eval-rst}\n')
                f2.write(f'.. autofunction:: {module_name}.{func}\n')
                f2.write('```\n\n')


def write_dochtree(f: TextIOWrapper, title: str, items: list[str]):
    f.write('```{toctree}\n')
    f.write(':maxdepth: 1\n')
    f.write(f':caption: {title}:\n')
    for text in items:
        if not text.startswith('_'):
            f.write(f"{text}\n")
    f.write('```\n\n')


if __name__ == "__main__":
    # Ensure the output directory exists
    os.makedirs('docs/source/_autogenerated', exist_ok=True)

    with open('docs/source/_autogenerated/index.md', 'w') as f:
        f.write('# Classes and functions\n\n')
        write_classes(f, ['DocumentWriter'], 'pyladoc', title='DocumentWriter Class')
        write_functions(f, ['*'], 'pyladoc', title='Functions')
        write_functions(f, ['*'], 'pyladoc.latex', title='Submodule latex')
